title: One Armed Man
author:
  name: Greg Raven
  email: greg@one-armed-man.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.

description: The right of the people to keep and bear arms shall not be infringed.

# Build settings

theme: minima

# the base hostname & protocol for your site

url: "https://www.one-armed-man.com"

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category-archive
    tags: tag-archive
  permalinks:
    tags: "/tag/:name/"
    category: "/category/:name/"

# Theme-specific settings

minima:
  skin: auto

# If you want to link only specific pages in your header, uncomment this
# and add the path to the pages in order as they should show up.

header_pages:
  - about.html
  - history-of-u-s-gun-control-laws.html
  - search.html

# Set to `true` to show excerpts on the homepage.

show_excerpts: true

paginate: 20
